trigger:
- develop

pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'mazes.cr-tests'

steps:
- task: Docker@2
  displayName: Build test image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile.build
